name: CLJ Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run:  lein deps
    - name: Run tests
      if: ${{ success() }}
      run: lein test
